fix ci

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -199,45 +199,103 @@ jobs:
         run: npm install
       - run: npm run build
 
+      # - name: Get the previous package id for the same package version
+      #   if: ${{ !(startsWith(github.ref, 'refs/tags/v')) }}
+      #   id: version-id
+      #   env:
+      #     PACKAGE_NAME: ${{ steps.package.outputs.name }}
+      #     PACKAGE_VERSION: ${{ steps.package.outputs.version }}
+      #   uses: actions/github-script@v7
+      #   with:
+      #     script: |
+      #       try {
+      #         const response = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
+      #           org: context.repo.owner,
+      #           package_name: process.env.PACKAGE_NAME,
+      #           package_type: 'npm'
+      #         });
+      #         const version = response.data.find(v => v.name === process.env.PACKAGE_VERSION);
+      #         if (version && version.id) {
+      #           return version.id;
+      #         } else {
+      #           console.error('Version not found');
+      #           return 0;
+      #         }
+      #       } catch (error) {
+      #         if (error.status === 404) {
+      #           console.error('Package not found or access denied');
+      #           return 0;
+      #         } else {
+      #           throw error; // re-throw the error if it's not a 404
+      #         }
+      #       }
       - name: Get the previous package id for the same package version
         if: ${{ !(startsWith(github.ref, 'refs/tags/v')) }}
         id: version-id
-        env:
-          PACKAGE_NAME: ${{ steps.package.outputs.name }}
-          PACKAGE_VERSION: ${{ steps.package.outputs.version }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            try {
-              const response = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
-                org: context.repo.owner,
-                package_name: process.env.PACKAGE_NAME,
-                package_type: 'npm'
-              });
-              const version = response.data.find(v => v.name === process.env.PACKAGE_VERSION);
-              if (version && version.id) {
-                return version.id;
-              } else {
-                console.error('Version not found');
-                return 0;
-              }
-            } catch (error) {
-              if (error.status === 404) {
-                console.error('Package not found or access denied');
-                return 0;
-              } else {
-                throw error; // re-throw the error if it's not a 404
-              }
-            }
+        run: |
+          ORG=${{ github.repository_owner }}
+          PACKAGE_NAME=${{ steps.package.outputs.name }}
+          PACKAGE_VERSION=${{ steps.package.outputs.version }}
+
+          response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/orgs/${ORG}/packages/npm/${PACKAGE_NAME}/versions")
+
+          # Extract HTTP status code
+          status_code="${response: -3}"
+
+          # Check if the request was successful (status code 2xx)
+          if [[ $status_code -eq 200 ]]; then
+            # Fetch response body
+            response_body=$(echo "${response}" | sed '$s/...$//')
+
+            # Parse JSON response with jq to find the version ID
+            version_id=$(echo "${response_body}" | jq -r --arg PACKAGE_VERSION "${PACKAGE_VERSION}" '
+            .[] | select(.name | startswith($PACKAGE_VERSION)) | .id')
+
+            # Check if version_id is not empty
+            if [[ -n "${version_id}" ]]; then
+              echo "Version ID found: ${version_id}"
+              echo "version_id=${version_id}" >> $GITHUB_OUTPUT
+            else
+              echo "Version not found"
+              echo "version_id=0" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "Package not found or access denied"
+            echo "version_id=0" >> $GITHUB_OUTPUT
+          fi
+
+      # # Remove previous push of that version
+      # - name: Delete package
+      #   if: ${{ !(startsWith(github.ref, 'refs/tags/v')) && steps.version-id.outputs.result != '0' }}
+      #   uses: actions/delete-package-versions@v5
+      #   with:
+      #     package-name: ${{ steps.package.outputs.name }}
+      #     package-type: 'npm'
+      #     package-version-ids: ${{ steps.version-id.outputs.result }}
 
       # Remove previous push of that version
       - name: Delete package
-        if: ${{ !(startsWith(github.ref, 'refs/tags/v')) && steps.version-id.outputs.result != '0' }}
-        uses: actions/delete-package-versions@v5
-        with:
-          package-name: ${{ steps.package.outputs.name }}
-          package-type: 'npm'
-          package-version-ids: ${{ steps.version-id.outputs.result }}
+        if: ${{ !(startsWith(github.ref, 'refs/tags/v')) && steps.version-id.outputs.version_id != '0' }}
+        run: |
+          ORG=${{ github.repository_owner }}
+          PACKAGE_NAME=${{ steps.package.outputs.name }}
+          VERSION_ID=${{ steps.version-id.outputs.version_id }}
+
+          # Delete the package version using GitHub API
+          response=$(curl -s -w "%{http_code}" -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/orgs/${ORG}/packages/npm/${PACKAGE_NAME}/versions/${VERSION_ID}")
+
+          # Extract HTTP status code
+          status_code="${response: -3}"
+
+          # Check if the request was successful (status code 2xx)
+          if [[ $status_code -eq 204 ]]; then
+            echo "Package version deleted successfully."
+          else
+            echo "Failed to delete package version. HTTP status code: $status_code"
+            exit 1
+          fi
 
       # Publish the package.
       # If it's from a git tag, the package is published to npmjs.com and 
@@ -269,104 +327,3 @@ jobs:
 
         env:
           NODE_AUTH_TOKEN: ${{ steps.package.outputs.secret }}
-
-  clean-up:
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    needs: openapi-typescript-angular
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-    steps:
-      - name: Delete Versions of Packages for Closed PRs
-        uses: actions/github-script@v7
-        with:
-          github-token: ${{ secrets.WORKFLOW_TOKEN }}
-          script: |
-            const org = context.repo.owner;
-            const repo = context.repo.repo;
-
-            const packageTypes = ['container', 'npm', 'maven', 'rubygems', 'docker', 'nuget'];
-
-            async function safeApiCall(apiPromise, description) {
-              try {
-                const response = await apiPromise;
-                console.log(`Success: ${description}`);
-                return response;
-              } catch (error) {
-                console.error(`API Error for ${description}:`, error);
-                return null;
-              }
-            }
-
-            const closedPrsResponse = await safeApiCall(
-              github.rest.pulls.list({
-                owner: org,
-                repo: repo,
-                state: 'closed'
-              }), 
-              'Fetching closed PRs'
-            );
-            if (!closedPrsResponse) return;
-
-            const closedPrNumbers = closedPrsResponse.data.map(pr => pr.number);
-
-            for (const packageType of packageTypes) {
-              console.log(`Checking package type: ${packageType}`);
-
-              let packagesResponse;
-              try {
-                packagesResponse = await github.rest.packages.listPackagesForOrganization({
-                  org: org,
-                  package_type: packageType
-                });
-              } catch (error) {
-                console.error(`Error fetching packages of type ${packageType}:`, error);
-                continue;
-              }
-
-              for (const package of packagesResponse.data) {
-                const packageName = package.name;
-                console.log(`Checking package: ${packageName}`);
-
-                const versionsResponse = await safeApiCall(
-                  github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
-                    org: org,
-                    package_type: packageType,
-                    package_name: packageName
-                  }),
-                  `Fetching versions for package ${packageName}`
-                );
-                if (!versionsResponse) continue;
-
-                for (const version of versionsResponse.data) {
-                  let prNumberMatch;
-                  if (packageType === 'container' || packageType === 'docker') {
-                    // For container and docker, use the tag
-                    const versionTags = version.metadata.container.tags;
-                    for (const tag of versionTags) {
-                      prNumberMatch = tag.match(/.(\d+)$/);
-                      if (prNumberMatch && closedPrNumbers.includes(parseInt(prNumberMatch[1]))) {
-                        break; // Break the loop if a matching PR number is found
-                      }
-                    }
-                  } else {
-                    // For maven, rubygems, nuget, use the version name
-                    prNumberMatch = version.name.match(/.(\d+)$/);
-                  }
-
-                  if (prNumberMatch && closedPrNumbers.includes(parseInt(prNumberMatch[1]))) {
-                    console.log(`Deleting package version ${version.id} of ${packageName} for closed PR #${prNumberMatch[1]}`);
-                    await safeApiCall(
-                      github.rest.packages.deletePackageVersionForOrg({
-                        org: org,
-                        package_type: packageType,
-                        package_name: packageName,
-                        package_version_id: version.id,
-                      }),
-                      `Deleting package version ${version.id} of ${packageName}`
-                    );
-                  }
-                }
-              }
-            }
